version: '3.9'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    volumes:
      - ./docker/postgres/nginx.conf:/docker-entrypoint-initdb.d/nginx.conf
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=Qwer1234


  url_shortener_golang_app:
    build: ./
    command: ./wait-for-postgres.sh db ./url_shortener_golang_app
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
    env_file:
      - .env
    environment:
      - DB_PASSWORD=Qwer1234